all:
  children:
    linux:
      hosts:
        attack-range-kali:
          ansible_host: "{{ lookup('env', 'ATTACK_RANGE_KALI_IP') }}"
      vars:
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_user: kali
    windows:
      hosts:
        attack-range-dc:
          ansible_host: "{{ lookup('env', 'ATTACK_RANGE_DC_IP') }}"
          ansible_winrm_operation_timeout_sec: 60
          ansible_winrm_read_timeout_sec: 70
          roles:
            - defender_for_endpoint
        attack-range-workstation:
          ansible_host: "{{ lookup('env', 'ATTACK_RANGE_WORKSTATION_IP') }}"
          ansible_winrm_operation_timeout_sec: 60
          ansible_winrm_read_timeout_sec: 70
          roles:
            - defender_for_endpoint
        attack-range-win11:
          ansible_host: "{{ lookup('env', 'ATTACK_RANGE_WIN11_IP') }}"
          ansible_winrm_operation_timeout_sec: 60
          ansible_winrm_read_timeout_sec: 70
          roles:
            - defender_for_endpoint
        attack-range-server2025:
          ansible_host: "{{ lookup('env', 'ATTACK_RANGE_SERVER2025_IP') }}"
          ansible_winrm_operation_timeout_sec: 60
          ansible_winrm_read_timeout_sec: 70
          roles:
            - defender_for_endpoint
      vars:
        ansible_connection: winrm
        ansible_password: YourSecurePassword123!AttackRange2024!
        ansible_port: '5985'
        ansible_user: azureuser
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: ntlm
